### ISSUE TITLE
Installation issues and element not showing content

### ISSUE THREAD

**Issue by DMTSource** [AKHXtern/paper-code-mirror#1]
I installed the component via bower. I attempted to use a paper-code-mirror example from the demo but the content code is not showing.

In order to get the code-mirror to work in my polymer app I had to copy the vendor dir from the paper-code-mirror directory within bower components to the home directory of the site in order to prevent the file require.min.js from throwing errors as it could not find the vendor folder. However, vendor has to exist in both locations to prevent import errors.

At this point I had no errors.  The code-mirror appears to be working however with formatting, number lines, and style being applied, but the initial text that should be shown is missing.

What is the correct installation process for using the paper-code-mirror with a site?

**Comment by dreammmr** [comment]
Hey, I just pushed a new version without require.js. So try again and let me know if it works well.

**Comment by DMTSource** [comment]
@AKHXtern thank you for the quick response! I re-bowered the package and no longer had errors due to vendor folder not being in root.

However, I am still not seeing the initial content inside the paper-code-mirror. Instead of showing any content it is blank(shows the cursor and "line 1"). I am trying to use examples from your demo code in the Polymer Starter Kit and one of its simple views in case that raises any red flags. 

Thanks again for the help.
